# Generated by Django 4.2.13 on 2024-06-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo1', models.ImageField(upload_to='details')),
                ('photo2', models.ImageField(upload_to='details')),
                ('photo3', models.ImageField(upload_to='details')),
                ('bio', models.CharField(max_length=100)),
                ('biography', models.CharField(max_length=100)),
                ('bioSub', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=60)),
                ('gitHub', models.CharField(max_length=60)),
                ('linkedIn', models.CharField(max_length=60)),
                ('instagram', models.CharField(max_length=60)),
                ('skillSub', models.CharField(max_length=60)),
                ('workscreenshot1', models.ImageField(upload_to='details')),
                ('workscreenshot2', models.ImageField(upload_to='details')),
                ('workscreenshot3', models.ImageField(upload_to='details')),
                ('workscreenshot5', models.ImageField(upload_to='details')),
                ('work1', models.CharField(max_length=60)),
                ('work2', models.CharField(max_length=60)),
                ('work3', models.CharField(max_length=60)),
                ('work4', models.CharField(max_length=60)),
            ],
        ),
    ]
