# Generated by Django 4.2.13 on 2024-06-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='skill1',
            field=models.CharField(default='true', max_length=60),
        ),
        migrations.AddField(
            model_name='details',
            name='skill2',
            field=models.CharField(default='true', max_length=60),
        ),
        migrations.AddField(
            model_name='details',
            name='skill3',
            field=models.CharField(default='true', max_length=60),
        ),
        migrations.AddField(
            model_name='details',
            name='skill4',
            field=models.CharField(default='true', max_length=60),
        ),
        migrations.AddField(
            model_name='details',
            name='skill5',
            field=models.CharField(default='true', max_length=60),
        ),
        migrations.AddField(
            model_name='details',
            name='skill6',
            field=models.CharField(default='true', max_length=60),
        ),
        migrations.AddField(
            model_name='details',
            name='skill7',
            field=models.CharField(default='true', max_length=60),
        ),
        migrations.AddField(
            model_name='details',
            name='skill8',
            field=models.CharField(default='true', max_length=60),
        ),
    ]
