# Generated by Django 4.2.13 on 2024-06-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_details_skill1_details_skill2_details_skill3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='banner',
            field=models.ImageField(default='true', upload_to='details'),
        ),
    ]
