# Generated by Django 4.2.13 on 2024-06-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_details_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='skillSub',
            field=models.CharField(max_length=200),
        ),
    ]
